version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "REPLACED_BY_CODEPIPELINE"
        LoadBalancerInfo:
          ContainerName: "khan-microservice-api"
          ContainerPort: 5000
