version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 615299769479.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - docker build -t khan-microservice-api .
      - docker tag khan-microservice-api:latest 615299769479.dkr.ecr.us-east-1.amazonaws.com/khan-microservice-api:latest
      - docker push 615299769479.dkr.ecr.us-east-1.amazonaws.com/khan-microservice-api:latest
  post_build:
    commands:
      - echo Writing imagedefinitions.json file...
      - printf '[{"name":"khan-microservice-api","imageUri":"615299769479.dkr.ecr.us-east-1.amazonaws.com/khan-microservice-api:latest"}]' > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - appspec.yaml
